### ISSUE TITLE
Inconsistency between code and paper

### ISSUE THREAD

**Issue by Enderlogic** [TURuibo/MVPC#1]
Hi Ruibo,

Your paper and code are both excellent, but I'm a bit confused by some inconsistency between them (maybe I got it wrong).

In CITest.R/gaussCItest.permc function, you define W as the parents of missing indicators of x, y and S. However, based on the definition of Permutation-based correction method in the reference paper, W should be the parents of Rx, Ry, Rz and **_Rw_**.

On the contrary, in CITest.R/gaussCItest.drw function, you include parents of Rw in W to compute the weights but this term is not used in the equation (5) in the paper. So I think you should only use the parents of Rx, Ry and Rz to compute this equation.

Hope you are being well. Looking forward to your replies.

Thanks and regards
Yang

**Comment by TURuibo** [comment]
Hi Yang, 

Thank you so much for raising the issue.

In the function CITest.R/gaussCItest.permc , **W** should be parent of of Rx, Ry, Rz and **Rw**. This will be fixed soon.

In the function CITest.R/gaussCItest.drw , **W** is also the parent of Rx, Ry, Rz and **Rw**. 
In the equation (5), **Va** includes **W**, as the paragraph above (5) said,  "In these cases, we consistently estimate the joint distribution P(**Va**) of concerned variables X, Y, and Z in a CI test and the direct causes **W** = Pa(Rx,Ry,Rz,**Rw**)". The reason is that if **W** also has missing values, the denominator in (5) requires the parent of W as well. 
For example, consider a very simple DAG: X --> W1 <--Y, X --> W2 <--Y,  W1 --> Rx, and W2 --> Rw1. Then denominator is P(Rx | W1, Rw1)P(Rw1|W2).

Best wishes,
Ruibo

**Comment by Enderlogic** [comment]
That makes sense. Thank you for your answers.

Besides, I have another question about the _Density ratio weighted_ correction method. Suppose there is a DAG G with variables **_V_** and some of them are not fully observed in the dataset. Since the joint distribution P(**_V_**) can be recovered from the observed dataset by equation (5). Can we directly do list-wise deletion on the observed dataset and run CI tests on the weighted list-wise deletion dataset instead of multiple weighted test-wise deletion datasets?

Actually, I have tried this naive idea on my toy dataset but its performance is very poor. So that I just want to know whether this is a reasonable method.

Thanks,
Yang

**Comment by TURuibo** [comment]
In theory, when the assumptions are satisfied, Eqn. (5) recovers the full data distribution. However, in practice, there may be many reasons for poor performance such as 
1. the assumptions: whether they are satisfied or not would be hard to say. And one violation of one variable may affect the overall performance ;
2. the sample size : you may throw away many data with list-wise deletion;
3. the density estimation methods may not perform well in high-dimension cases.
